name: "TestSpaces"
description: "TestSpaces is a tool!"
businessUnit: "DevFactory"
decisions:
  - id: "1"
    date: 2018-11-29T16:04:32Z
    title: "Docker as the containerization technology platform"
    status: Accepted
    content: "## Context\nWe need to choose the default containerization technology that DevSpaces will support\n\n## Decision\nWe will choose Docker as the default platform\n\n## Consequences\nWe will only be able to support Linux based environments for the moment until Docker is able to support full Windows workspaces"

  - id: "2"
    date: 2019-11-19T19:07:15Z
    title: "Kubernetes as the container management platform"
    status: Accepted
    content: "## Context\nWe need an orchestration platform that will help us manage all the containers.\n\n## Decision\nKubernetes will be the container orchestration platform\n\n## Consequences."

model:
  people:
    - id: "1"
      path: "@Developer"
      description: "Developer building software"
      tags:
        - "DevSpaces System View"
        - "Trilogy System View"
        - "DevSpaces Container View"
      relationships:
        - id: "17"
          action: USES
#          with: "c4://GitHub"
          with: "7"
          description: "as a version control system"

        - id: "18"
          action: USES
#          with: "c4://DevSpaces"
          with: "8"
          description: "to devolop software"

        - id: "19"
          action: USES
#          with: "c4://Trilogy Google G Suite"
#          with: "c4://Trilogy Google G Suite"
          with: "6"
          description: "inter-team collaboration"

        - id: "20"
          action: USES
#          with: "c4://DevSpaces/DevSpaces CLI"
          with: "9"
          description: "creates and manages dev spaces"

    - id: "2"
      path: "@SaasOps"
      description: "SaasOps operating system"
      tags:
        - "DevSpaces System View"
        - "Trilogy System View"
        - "DevSpaces Container View"
      relationships:
        - id: "21"
          action: USES
#          with: "c4://GitHub"
          with: "7"
          description: "as a version control system"

        - id: "22"
          action: USES
#          with: "c4://DevSpaces"
          with: "8"
          description: "to manage cluster"

        - id: "23"
          action: USES
#          with: "c4://Trilogy Google G Suite"
          with: "6"
          description: "inter-team collaboration"

        - id: "24"
          action: USES
#          with: "c4://DevSpaces/DevSpaces Web Application"
          with: "11"
          description: "to manage instances"

    - id: "3"
      path: "@PCA"
      description: "Product Chief Architect"
      tags:
        - "Trilogy System View"
      relationships:
        - id: "25"
          action: USES
#          with: "c4://GitHub"
          with: "7"
          description: "as a version control system"

        - id: "26"
          action: USES
#          with: "c4://XO Chat"
          with: "4"
          description: "to communicate with team"

        - id: "27"
          action: USES
#          with: "c4://Trilogy Google G Suite"
          with: "6"
          description: "inter-team collaboration"

  systems:
    - id: "4"
      path: "c4://XO Chat"
      description: "Realtime team communication"
      tags:
        - "Trilogy System View"

    - id: "5"
      path: "c4://SalesForce"
      description: "SalesForce rules"

    - id: "6"
      path: "c4://Trilogy Google G Suite"
      description: "Team collaboration via sheets, docs and presentations"
      tags:
        - "Trilogy System View"

    - id: "7"
      path: "c4://GitHub"
      description: "Hosts code and used for identity management"
      tags:
        - "DevSpaces System View"
        - "DevSpaces Container View"

    - id: "8"
      path: "c4://DevSpaces"
      description: "allows developers to collaborate"
      tags:
        - "DevSpaces System View"

  containers:
    - id: "9"
      path: "c4://DevSpaces/DevSpaces CLI"
      description: "Command Line Interface for interacting with DevSpaces Backend"
      technology: "C++"
      relationships:
        - id: "28"
          action: USES
#          with: "c4://DevSpaces/DevSpaces API"
          with: "12"
          description: "to manipulate dev spaces"

    - id: "10"
      path: "c4://DevSpaces/DevSpaces Backend"
      description: "Restful API providing capabilities for interacting with a DevSpace"
      technology: "Spring Boot"
      tags:
        - "DevSpaces Container View"
      relationships:
        - id: "29"
          action: USES
#          with: "c4://DevSpaces/DevSpaces API"
          with: "12"
          description: "to manipulate dev spaces"

    - id: "11"
      path: "c4://DevSpaces/DevSpaces Web Application"
      description: "Manage dev spaces"
      technology: "Angular"
      tags:
        - "DevSpaces Container View"
      relationships:
        - id: "30"
          action: USES
#          with: "c4://DevSpaces/DevSpaces Backend"
          with: "10"
          description: "Frontend queries backend"

    - id: "12"
      path: "c4://DevSpaces/DevSpaces API"
      description: "API to programmatically create/manage dev spaces"
      technology: "Spring Boot"
      tags:
        - "DevSpaces Container View"

  components:
    - id: "13"
      path: "c4://DevSpaces/DevSpaces API/Sign In Controller"
      description: "Allows users to sign in"
      technology: "Spring MVC Rest Controller"
      tags:
        - "DevSpaces API Component View"
      relationships:
        - id: "31"
          action: USES
#          with: "c4://DevSpaces/DevSpaces API/Security Component"
          with: "14"
          description: "Authorizes user"


    - id: "14"
      path: "c4://DevSpaces/DevSpaces API/Security Component"
      description: "Provides functionality related to signing in, changing passwords, permissions, etc."
      technology: "Spring Bean"
      tags:
        - "DevSpaces API Component View"

    - id: "15"
      path: "c4://DevSpaces/DevSpaces API/Reset Password Controller"
      description: "Allows users to reset their passwords"
      technology: "Spring MVC Rest Controller"
      tags:
        - "DevSpaces API Component View"
      relationships:
        - id: "32"
          action: USES
#          with: "c4://DevSpaces/DevSpaces API/Security Component"
          with: "14"
          description: "Authorizes user"

        - id: "33"
          action: USES
#          with: "c4://DevSpaces/DevSpaces API/E-mail Component"
          with: "16"
          description: "sends new password"

    - id: "16"
      path: "c4://DevSpaces/DevSpaces API/E-mail Component"
      description: "Sends emails to users"
      technology: "Spring MVC Rest Controller"
      tags:
        - "DevSpaces API Component View"

views:
  systemViews:
    - name: "DevSpaces"
      systemPath: "c4://DevSpaces"
      description: "Internal Trilogy users view of DevSpaces system"
      tags:
        - "DevSpaces System View"
      references:
        - path: "@Developer"
        - path: "@PCA"
        - path: "c4://GitHub"
        - path: "c4://Trilogy Google G Suite"
        - path: "c4://SalesForce"

    - name: "Trilogy Google G Suite"
      systemPath: "c4://Trilogy Google G Suite"
      description: "Trilogy inter-team communication"
      tags:
        - "Trilogy System View"

  containerViews:
    - name: "DevSpaces API Container"
      systemPath: "c4://DevSpaces"
      description: "DevSpaces Container"
      tags:
        - "DevSpaces Container View"

  componentViews:
    - name: "DevSpaces API Components"
      containerPath: "c4://DevSpaces/DevSpaces API"
      description: "DevSpaces API Components"
      tags:
        - "DevSpaces API Component View"
