name: arch-as-code ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build
      env: # Or as an environment variable
        STRUCTURIZR_API_KEY: ${{ secrets.TEST_STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.TEST_STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.TEST_STRUCTURIZR_WORKSPACE_ID }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Push Test Coverage
      run: ./scripts/push-to-code-coverage.sh
      env: # Or as an environment variable
        STRUCTURIZR_API_KEY: ${{ secrets.TEST_STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.TEST_STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.TEST_STRUCTURIZR_WORKSPACE_ID }}
        GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}

    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: ./gradlew run --args="publish ./documentation/products/arch-as-code"
      env:
        STRUCTURIZR_API_KEY: ${{ secrets.STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.PROD_STRUCTURIZR_WORKSPACE_ID }}

#  release:
#    needs: build
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [windows-latest, ubuntu-latest, macOS-latest]
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#
#      - name: Test Installation on macOS & Ubuntu
#        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
#        run: ./scripts/install/${{ matrix.os }}/install.sh
#        env:
#          STRUCTURIZR_API_KEY: ${{ secrets.TEST_STRUCTURIZR_API_KEY }}
#          STRUCTURIZR_API_SECRET: ${{ secrets.TEST_STRUCTURIZR_API_SECRET }}
#          STRUCTURIZR_WORKSPACE_ID: ${{ secrets.TEST_STRUCTURIZR_WORKSPACE_ID }}
#
#      - name: Test Installation on Windows
#        if: matrix.os == 'windows-latest'
#        run: .\scripts\install\${{ matrix.os }}\install.ps1
#        shell: pwsh
#        env:
#          STRUCTURIZR_API_KEY: ${{ secrets.TEST_STRUCTURIZR_API_KEY }}
#          STRUCTURIZR_API_SECRET: ${{ secrets.TEST_STRUCTURIZR_API_SECRET }}
#          STRUCTURIZR_WORKSPACE_ID: ${{ secrets.TEST_STRUCTURIZR_WORKSPACE_ID }}