name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build
      env: # Or as an environment variable
        STRUCTURIZR_API_KEY: ${{ secrets.TEST_STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.TEST_STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.TEST_STRUCTURIZR_WORKSPACE_ID }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Push Test Coverage
      run: ./scripts/push-to-code-coverage.sh
      env: # Or as an environment variable
        STRUCTURIZR_API_KEY: ${{ secrets.TEST_STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.TEST_STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.TEST_STRUCTURIZR_WORKSPACE_ID }}
        GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}

    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: ./gradlew run --args="publish ./documentation/products/arch-as-code"
      env:
        STRUCTURIZR_API_KEY: ${{ secrets.STRUCTURIZR_API_KEY }}
        STRUCTURIZR_API_SECRET: ${{ secrets.STRUCTURIZR_API_SECRET }}
        STRUCTURIZR_WORKSPACE_ID: ${{ secrets.PROD_STRUCTURIZR_WORKSPACE_ID }}
